// <auto-generated />
using System;
using E_Commerce.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce.Migrations
{
    [DbContext(typeof(DbContesto))]
    [Migration("20240305145021_create")]
    partial class create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("E_Commerce.Models.Clienti", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("E_Commerce.Models.Ordini", b =>
                {
                    b.Property<int>("IdOrdini")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdini"));

                    b.Property<DateTime>("DataOrdine")
                        .HasColumnType("datetime2");

                    b.Property<string>("DettagliOrdini")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSpedizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsernameCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdOrdini");

                    b.HasIndex("UsernameCliente");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("E_Commerce.Models.Prodotti", b =>
                {
                    b.Property<int>("IdProdotto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdotto"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Prezzo")
                        .HasColumnType("float");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("IdProdotto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("E_Commerce.Models.Ordini", b =>
                {
                    b.HasOne("E_Commerce.Models.Clienti", "Cliente")
                        .WithMany("OrdiniCliente")
                        .HasForeignKey("UsernameCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("E_Commerce.Models.Prodotti", b =>
                {
                    b.HasOne("E_Commerce.Models.Categorie", "Categoria")
                        .WithMany("Prodotti")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("E_Commerce.Models.Categorie", b =>
                {
                    b.Navigation("Prodotti");
                });

            modelBuilder.Entity("E_Commerce.Models.Clienti", b =>
                {
                    b.Navigation("OrdiniCliente");
                });
#pragma warning restore 612, 618
        }
    }
}
